GIT_URL = 'https://github.com/bombeelu/bombeeX'
GIT_BRANCH = 'master'
ISSUE_URL = 'https://github.com/bombeelu/bombeeX/issues'
SEARX_URL = 'https://bombee.land'
DOCS_URL = 'https://bombeelu.github.io/bombeeX'
PUBLIC_INSTANCES = 'https://searx.space'
